### ISSUE TITLE
Empty Dashboard and wrong data type

### ISSUE THREAD

**Issue by berta24** [czantoine/microsoft-sql-server-with-grafana#1]
Hello, i would really like to use your dashboard since it's well made and already ready, but when i load it i have this situation:
![image](https://github.com/user-attachments/assets/2cdb5530-a48d-4ee9-ae29-2946951d826f)

all the query are empty and they get created as Prometheus type
![image](https://github.com/user-attachments/assets/6f82eeaa-579d-4c3f-81f3-b5e41ccd1842)

i've added the MSSQL connection and tested it, it works and can see all db, tables and data.
![image](https://github.com/user-attachments/assets/c33a5a7d-af6b-4170-80aa-67fcd27a504f)
![image](https://github.com/user-attachments/assets/66f533e7-ff13-4249-bbb0-f48bf9edee83)

Hope you can help me, thanks in advance

**Comment by berta24** [comment]
Never mind, i found a solution, i had to set MSSQL to default data source, i dont know why but it worked

**Comment by czantoine** [comment]
Hello, I changed the UID and the version of grafana into the json file, it's better now! Thanks for your comments
